### ISSUE TITLE
Redis and Resource Owner Password Credentials not working.

### ISSUE THREAD

**Issue by ShankzPatil** [eztier/authorization-server#1]
Redis and Resource Owner Password Credentials not working.
lots of errors present in module.

**Comment by once-ler** [comment]
The oauth2orize server instance is used by the db module.  

In the validate module, it doesn't have a reference to the oauth2orize server and is passing nothing to the db module.

I need to see if making oauth2orize server a singleton or a global is the right approach or just passing the server reference to the validate module.

**Comment by once-ler** [comment]
@ShankzPatil Resource Owner Password Credentials should work now.

**Comment by once-ler** [comment]
Closing this issue since there's been no response in a month.
